name: hotel_de_luna
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  
  table_calendar: ^3.2.0
  font_awesome_flutter: ^10.7.0
=======
  table_calendar: ^3.0.9

  font_awesome_flutter: ^10.12.0

>>>>>>> main

  # UI & Animations
  concentric_transition: ^1.0.3
  getwidget: ^7.0.0
  lottie: ^3.3.2

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  qr_flutter: ^4.1.0

  # Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  #Socials
  url_launcher: ^6.3.2



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/andheri_img/
    - assets/bandra_img/
    - assets/borivali_img/
    - assets/churchgate_img/

