name: hotel_de_luna
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  concentric_transition: ^1.0.3
  getwidget: ^7.0.0
  lottie: ^3.3.2
  google_fonts: ^6.2.1
  firebase_core: ^4.4.0

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

  # Fonts
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
